# Generated by Django 2.1.7 on 2020-11-29 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201129_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=24, validators=[django.core.validators.MinLengthValidator(24)])),
                ('file', models.FileField(upload_to='')),
                ('choice', models.CharField(choices=[('encrypt', 'encrypt'), ('decrypt', 'decrypt')], max_length=20)),
            ],
        ),
    ]
